### ISSUE TITLE
Baker's % Issue

### ISSUE THREAD

**Issue by phen-om** [hendricius/pizza-dough#70] opened 2020-12-06 03:24 UTC
I note that the water noted under "ingredients" is stated as 60% and that the calculation which follows shows the amount as 120 grams of warm water - correct math. BUT, when approaching the 'calculator' the baker's % is stated at 65%.  Quote: "Remember – the amount of water in one pizza should be 65% of the mass of the flour – so how much flour do you actually need for a 220 gram pizza?" Question: Which baker's percent is actually intended?

**Comment by hendricius** [comment] 2021-12-27 14:02
Should be fixed here: https://github.com/hendricius/pizza-dough/pull/85. If not please re-open

**Closed by hendricius** 2021-12-27 14:02 UTC

**Comment by tomdaly** [comment] 2021-12-31 17:06
hi @hendricius, figured I'd comment here instead of creating a new issue - this typo is still apparent in the README, so I've just created #92 to fix this as it confused me at first. let me know if this was intended to still be 65% and I can close the PR. thanks!
